pipeline {
    agent any

    /* 
     * Optional: If Maven or JDK are configured in your Jenkins Global Tool Configuration
     * (Manage Jenkins -> Tools), you can uncomment and adjust the names below:
     *
     * tools {
     *     maven 'Maven'
     *     jdk 'JDK_17'
     * }
     */

    parameters {
        string(
            name: 'TEST_RUNNER',
            defaultValue: 'ApiRunner',
            description: 'Name of the Test Runner class to execute (default: ApiRunner)'
        )
    }

    environment {
        MAVEN_OPTS = '-Dfile.encoding=UTF-8'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                echo 'Checking out source code from SCM...'
                checkout scm
            }
        }

        stage('Run API Tests & Generate Allure Report') {
            steps {
                script {
                    echo "Executing API Tests using runner: ${params.TEST_RUNNER}"

                    // Executes test and generates Allure HTML report via Maven (requires NO Allure CLI installed on Jenkins server)
                    if (isUnix()) {
                        sh "mvn clean test -Dtest=${params.TEST_RUNNER} allure:report"
                    } else {
                        bat "mvn clean test -Dtest=${params.TEST_RUNNER} allure:report"
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Processing test results and archiving reports...'

            // 1. Publish surefire JUnit XML test results in Jenkins UI
            junit testResults: '**/target/surefire-reports/*.xml', allowEmptyResults: true

            // 2. Archive Cucumber HTML Report
            archiveArtifacts artifacts: 'target/cucumber-reports.html', allowEmptyArchive: true

            // 3. Archive Allure HTML Report generated by Maven (Self-contained, requires no Allure CLI on Jenkins server)
            archiveArtifacts artifacts: 'target/site/allure-maven-plugin/**', allowEmptyArchive: true

            /* 
             * Optional: If you have configured Allure CLI in Jenkins Global Tools:
             * (Manage Jenkins -> Tools -> Allure Commandline, named e.g. 'Allure'),
             * you can uncomment the block below to publish via Jenkins Allure Plugin:
             *
             * allure([
             *     commandline: 'Allure',
             *     includeProperties: false,
             *     jdk: '',
             *     properties: [],
             *     reportBuildPolicy: 'ALWAYS',
             *     results: [[path: 'target/allure-results']]
             * ])
             */
        }
        success {
            echo 'Pipeline execution finished successfully!'
        }
        failure {
            echo 'Pipeline execution failed! Check test reports and logs for details.'
        }
    }
}
